# Generated by Django 3.2.15 on 2022-09-24 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_setting'),
        ('invoices', '0002_auto_20220923_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('15 Días', '15 Días'), ('30 Días', '30 Días'), ('45 Días', '45 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unique_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.product')),
            ],
        ),
    ]
