# Generated by Django 4.1.1 on 2022-09-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoice",
            "0002_invoice_settings_client_clientlogo_client_taxnumber_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOG", "Bogota"),
                    ("ANT", "Antioquia"),
                    ("ATL", "Atlantico"),
                    ("BOL", "Bolivar"),
                ],
                max_length=100,
            ),
        ),
    ]
