# Generated by Django 4.1.1 on 2022-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_alter_client_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("COP", "COP")], default="R", max_length=100
            ),
        ),
    ]
