# Generated by Django 4.1.1 on 2022-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_alter_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("COP", "COP")], default="COP", max_length=100
            ),
        ),
    ]
