# Generated by Django 4.1.1 on 2022-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_alter_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Borrador", "Borrador"),
                    ("Enviado", "Enviado"),
                    ("Pagado", "Pagado"),
                    ("Cancelado", "Cancelado"),
                    ("Vencido", "Vencido"),
                ],
                default="Borrador",
                max_length=100,
            ),
        ),
    ]
