# Generated by Django 4.1.1 on 2022-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="paymentTerms",
            field=models.CharField(
                choices=[
                    ("15 Dias", "15 Dias"),
                    ("30 Dias", "30 Dias"),
                    ("45 Dias", "45 Dias"),
                    ("60 Dias", "60 Dias"),
                    ("90 Dias", "90 Dias"),
                ],
                default="15 Dias",
                max_length=100,
            ),
        ),
    ]
